server:
  port: 8088

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/url-feeder
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

url-feeder-ms:
  kafka:
    topics:
      kafka-topics:
        text-html: html_topic
        image-jpeg: jpg_topic
        application-pdf: pdf_topic

  cool-down: 7
